# Copyright (c) 2026 Arvindra Sehmi
# Licensed under the MIT License — see LICENSE for details.

"""Mock chat provider — a complete FastAPI implementation of the reference
protocol (chat_tree/providers/reference.py), with a canned "LLM" that echoes
the prompt and demonstrates every typed block the canvas can render (text,
tool, script, metric, table, chart, mermaid, question) — including both ways
a mermaid diagram can arrive: a structured `kind: "mermaid"` block, and one
embedded inline as a ```mermaid fence inside the ordinary text reply. Include
the word "break" in the prompt to get deliberately-broken mermaid source in
BOTH paths instead, for exercising the renderer's fail-soft path.

Run it:
    .venv\\Scripts\\uvicorn mock_provider:app --port 9000

Point the canvas at it (.env), then restart `reflex run`:
    CHAT_API_PROVIDER=reference
    CHAT_API_BASE_URL=http://localhost:9000

State is in-memory: restarting the mock clears all history (the canvas will
then warn that nodes have no backend content and offer prompt-only reruns —
which is also a handy way to exercise that path).
"""

import asyncio
import json
import uuid
from typing import Any, Dict, List

from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.responses import StreamingResponse

app = FastAPI(title="chat-tree-canvas mock provider", version="1.0")

SESSIONS: Dict[str, str] = {}  # token -> user_id
HISTORY: Dict[str, List[Dict[str, Any]]] = {}  # node_id -> message rows


def _require_session(token: str | None) -> str:
    if not token or token not in SESSIONS:
        raise HTTPException(status_code=401, detail="Invalid or missing session token")
    return SESSIONS[token]


@app.get("/health")
def health() -> dict:
    return {"status": "ok", "provider": "mock"}


@app.post("/session")
async def mint_session(request: Request) -> dict:
    body = await request.json()
    user_id = (body.get("user_id") or "anonymous").strip() or "anonymous"
    token = uuid.uuid4().hex
    SESSIONS[token] = user_id
    return {"session_token": token}


@app.get("/history/{node_id}")
def get_history(node_id: str, x_session_token: str | None = Header(None)) -> dict:
    _require_session(x_session_token)
    return {"messages": HISTORY.get(node_id, [])}


@app.delete("/history/{node_id}/{round_num}")
def delete_round(
    node_id: str, round_num: int, x_session_token: str | None = Header(None)
) -> dict:
    _require_session(x_session_token)
    if node_id not in HISTORY:
        raise HTTPException(status_code=404, detail="Unknown node")
    HISTORY[node_id] = [
        m for m in HISTORY[node_id] if m.get("round", 0) != round_num
    ]
    if not HISTORY[node_id]:
        del HISTORY[node_id]
    return {"deleted": round_num}


def _demo_figure() -> str:
    """A small Plotly figure so the chart renderer gets exercised."""
    return json.dumps(
        {
            "data": [
                {"type": "scatter", "mode": "lines+markers",
                 "name": "signal", "y": [2, 4, 3, 6, 5, 8, 7]},
                {"type": "bar", "name": "volume", "y": [1, 2, 1, 3, 2, 4, 3]},
            ],
            "layout": {"title": {"text": "Mock chart"}},
        }
    )


def _mock_events(user_id: str, message: str, round_num: int):
    """The canned exchange: one of every block kind the canvas renders."""
    inline_mermaid_code = "graph TD; A--" if "break" in message.lower() else (
        "graph TD; A[Prose]-->B[Fenced code block]-->C[Rendered inline]"
    )
    reply = (
        f"**Mock provider** answering *{user_id}* (round {round_num}).\n\n"
        f"You said:\n\n> {message[:400]}\n\n"
        "This response demonstrates every typed block the canvas renders, "
        "including a mermaid diagram embedded inline in this very paragraph:\n\n"
        f"```mermaid\n{inline_mermaid_code}\n```\n\n"
        "...and the prose continues normally after it. Wire your own backend "
        "by implementing this protocol — see `docs/PROVIDERS.md`."
    )
    yield {"type": "route_decision", "data": {"mode": "mock_echo"}}
    # stream the text in small deltas so the canvas visibly streams
    for i in range(0, len(reply), 24):
        yield {"type": "text_delta", "data": {"delta": reply[i : i + 24]}}
    yield {"type": "tool_call", "data": {"tool": "mock_lookup"}}
    yield {"type": "tool_result", "data": {"tool": "mock_lookup", "denied": False}}
    yield {
        "type": "sandbox_start",
        "data": {"code": "# generated by the mock provider\nprint('hello from the mock')\n"},
    }
    yield {
        "type": "tool_call_result",
        "data": {"kind": "metric", "label": "Prompt length", "value": len(message), "unit": "chars"},
    }
    yield {
        "type": "tool_call_result",
        "data": {
            "kind": "table",
            "title": "Mock table",
            "records": [
                {"key": "provider", "value": "mock"},
                {"key": "round", "value": round_num},
                {"key": "user", "value": user_id},
            ],
        },
    }
    yield {
        "type": "tool_call_result",
        "data": {"kind": "chart", "title": "Mock chart", "figure_json": _demo_figure()},
    }
    if "break" in message.lower():
        # Deliberately-broken mermaid source, for exercising the renderer's
        # fail-soft path without restarting the provider.
        yield {
            "type": "tool_call_result",
            "data": {"kind": "mermaid", "title": "Broken diagram", "code": "graph TD; A--"},
        }
    else:
        yield {
            "type": "tool_call_result",
            "data": {
                "kind": "mermaid",
                "title": "Mock flow",
                "code": (
                    "graph TD; A[Start]-->B{Above 0.618?}; "
                    "B-->|yes| C[Hold]; B-->|no| D[Sell]"
                ),
            },
        }
    yield {
        "type": "tool_call_result",
        "data": {"kind": "question", "text": "What's your risk tolerance?"},
    }
    yield {"type": "done", "data": {"round": round_num}}


@app.post("/chat")
async def chat(request: Request, x_session_token: str | None = Header(None)):
    user_id = _require_session(x_session_token)
    body = await request.json()
    node_id = body.get("node_id") or ""
    message = body.get("message") or ""
    if not node_id or not message:
        raise HTTPException(status_code=422, detail="node_id and message are required")

    rows = HISTORY.setdefault(node_id, [])
    round_num = sum(1 for m in rows if m.get("role") == "assistant")
    rows.append({"role": "user", "text": message, "round": round_num})

    async def stream():
        events: List[Dict[str, Any]] = []
        text_parts: List[str] = []
        for event in _mock_events(user_id, message, round_num):
            if event["type"] == "text_delta":
                text_parts.append(event["data"]["delta"])
            if event["type"] not in ("done",):
                events.append(event)
            yield f"data: {json.dumps(event)}\n\n"
            await asyncio.sleep(0.03)  # visible streaming
        # persist the assistant row so hydration replays the same blocks
        rows.append(
            {
                "role": "assistant",
                "text": "".join(text_parts),
                "events": events,
                "result": {},
                "mode": "mock_echo",
                "round": round_num,
                "interrupted": False,
            }
        )

    return StreamingResponse(stream(), media_type="text/event-stream")
